development:
  adapter: mysql2
  username: "root"
  password: "password"
  host: "localhost"
  database: "name_db"
test:
  adapter: mysql2
  username: "root"
  password: "password"
  host: "localhost"
  database: "name_db"
production:
  adapter: mysql2
  username: "root"
  password: "password"
  host: "localhost"
  database: "name_db"
staging:
  adapter: mysql2
  username: "root"
  password: "password"
  host: "localhost"
  database: "name_db"
