development:
  adapter: mysql2
  username: ENV['MYSQL_USERNAME']
  password: ENV['MYSQL_PASSWORD']
test:
  adapter: mysql2
  username: ENV['MYSQL_USERNAME']
  password: ENV['MYSQL_PASSWORD']
production:
  adapter: mysql2
  username: ENV['MYSQL_USERNAME']
  password: ENV['MYSQL_PASSWORD']
